# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd11120cab444f2fde62cd7dde92f649ddd411adfb16bc30661b80befe05462b1dd44c6c3620618defd1d6332fea921e87d306a6f69161a4667238f9b95ad213

test:
  secret_key_base: 064f0c6cc5180c17d9324c98f2873dd3e77eedaf01cda3883051cb134b04734c07b22eb6a6fcc72848aa3587e6ba2d6b9e664e37e1bf1bd1f797359798a9de28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
